/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlogDeployPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  blogPath: "C:\\Users\\yelfs\\Desktop\\My-Blog",
  postsSubdir: "source\\_posts",
  deployDelayMinutes: 10,
  autoPush: true,
  topImg: "transparent",
  comments: false,
  commitTemplate: "publish: {{title}} via Obsidian",
  picgoServer: "http://127.0.0.1:36677"
};
var BlogDeploySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Blog Deploy Settings" });
    new import_obsidian.Setting(containerEl).setName("Blog local path").setDesc("Absolute path to your Hexo/Hugo blog directory (git repo root)").addText(
      (text) => text.setPlaceholder("C:\\Users\\yelfs\\Desktop\\My-Blog").setValue(this.plugin.settings.blogPath).onChange(async (value) => {
        this.plugin.settings.blogPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Posts subdirectory").setDesc("Relative path from blog root to the _posts folder").addText(
      (text) => text.setPlaceholder("source/_posts").setValue(this.plugin.settings.postsSubdir).onChange(async (value) => {
        this.plugin.settings.postsSubdir = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Deploy delay (minutes)").setDesc("How many minutes to wait before auto-deploy (0 = immediate)").addSlider(
      (slider) => slider.setLimits(0, 60, 1).setValue(this.plugin.settings.deployDelayMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.deployDelayMinutes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto git push").setDesc("Automatically commit and push to GitHub after deploying").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoPush).onChange(async (value) => {
        this.plugin.settings.autoPush = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Comments enabled").setDesc("Default value for 'comments' in frontmatter").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.comments).onChange(async (value) => {
        this.plugin.settings.comments = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Top image").setDesc("Default value for 'top_img' in frontmatter (e.g., 'transparent' or a URL)").addText(
      (text) => text.setValue(this.plugin.settings.topImg).onChange(async (value) => {
        this.plugin.settings.topImg = value || "transparent";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Commit message template").setDesc("Use {{title}} as placeholder for the post title").addText(
      (text) => text.setPlaceholder("publish: {{title}} via Obsidian").setValue(this.plugin.settings.commitTemplate).onChange(async (value) => {
        this.plugin.settings.commitTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("PicGo server URL").setDesc("Local PicGo upload server address (PicGo \u2192 \u8BBE\u7F6E \u2192 Server)").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:36677").setValue(this.plugin.settings.picgoServer).onChange(async (value) => {
        this.plugin.settings.picgoServer = value || "http://127.0.0.1:36677";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/deployer.ts
var path3 = __toESM(require("path"));
var fs2 = __toESM(require("fs"));

// src/frontmatter.ts
function parseFrontmatter(content) {
  if (!content.startsWith("---")) {
    return { frontmatter: null, body: content };
  }
  const endIndex = content.indexOf("---", 3);
  if (endIndex === -1) {
    return { frontmatter: null, body: content };
  }
  const fmSection = content.substring(3, endIndex).trim();
  const body = content.substring(endIndex + 3).trimStart();
  const lines = fmSection.split("\n");
  const frontmatter = {};
  for (const line of lines) {
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1)
      continue;
    const key = line.substring(0, colonIndex).trim();
    let value = line.substring(colonIndex + 1).trim();
    if (value === "false") {
      frontmatter[key] = false;
    } else if (value === "true") {
      frontmatter[key] = true;
    } else {
      frontmatter[key] = value;
    }
  }
  return { frontmatter, body };
}
function generateFrontmatterString(fm) {
  let result = "---\n";
  result += `title: ${fm.title}
`;
  result += `tags: ${fm.tags}
`;
  result += `date: ${fm.date}
`;
  result += `top_img: ${fm.top_img}
`;
  result += `comments: ${fm.comments}
`;
  result += "---\n\n";
  return result;
}
function generateFrontmatter(title, tags, topImg, comments) {
  const today = /* @__PURE__ */ new Date();
  const y = today.getFullYear();
  const m = String(today.getMonth() + 1).padStart(2, "0");
  const d = String(today.getDate()).padStart(2, "0");
  return {
    title,
    tags,
    date: `${y}-${m}-${d}`,
    top_img: topImg,
    comments
  };
}
function extractTitleFromContent(content) {
  const match = content.match(/^#\s+(.+)$/m);
  if (match && match[1]) {
    return match[1].trim();
  }
  return "";
}
function extractTagsFromPath(filePath) {
  const parts = filePath.replace(/\\/g, "/").split("/");
  if (parts.length <= 1) {
    return "";
  }
  const folders = parts.slice(0, -1);
  return folders.filter((f) => f.trim().length > 0 && !f.startsWith(".")).join(", ");
}

// src/git.ts
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var GitOperator = class {
  constructor(repoPath) {
    this.repoPath = repoPath;
  }
  exec(cmd) {
    const options = {
      cwd: this.repoPath,
      encoding: "utf-8",
      timeout: 3e4,
      stdio: ["pipe", "pipe", "pipe"],
      windowsHide: true
    };
    try {
      const stdout = (0, import_child_process.execSync)(cmd, options);
      return { stdout: stdout.toString().trim(), stderr: "" };
    } catch (e) {
      return {
        stdout: e.stdout?.toString().trim() || "",
        stderr: e.stderr?.toString().trim() || e.message
      };
    }
  }
  isRepo() {
    const dir = path.resolve(this.repoPath);
    const dotGit = path.join(dir, ".git");
    try {
      require("fs").statSync(dotGit);
      return true;
    } catch {
      return false;
    }
  }
  hasUnsavedChanges() {
    const { stdout } = this.exec("git status --porcelain");
    return stdout.length > 0;
  }
  add(files) {
    const fileArgs = files.map((f) => `"${f}"`).join(" ");
    const { stderr } = this.exec(`git add ${fileArgs}`);
    if (stderr) {
      console.error("git add error:", stderr);
      return false;
    }
    return true;
  }
  commit(message) {
    const { stderr } = this.exec(`git commit -m "${message.replace(/"/g, '\\"')}"`);
    if (stderr && !stderr.includes("nothing to commit") && !stderr.includes("nothing added")) {
      console.error("git commit error:", stderr);
      return false;
    }
    return true;
  }
  push(branch = "main") {
    const { stdout, stderr } = this.exec(`git push origin ${branch}`);
    if (stderr && stderr.includes("error")) {
      return { success: false, message: stderr };
    }
    return { success: true, message: stdout || "Pushed successfully" };
  }
  getCurrentBranch() {
    const { stdout } = this.exec("git rev-parse --abbrev-ref HEAD");
    return stdout || "main";
  }
  getCommitMessageTemplate(template, title) {
    return template.replace("{{title}}", title);
  }
};

// src/images.ts
var http = __toESM(require("http"));
var fs = __toESM(require("fs"));
var path2 = __toESM(require("path"));
function extractImageRefs(content) {
  const refs = [];
  const seen = /* @__PURE__ */ new Set();
  const mdRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  let match;
  while ((match = mdRegex.exec(content)) !== null) {
    const target = match[2];
    if (seen.has(target))
      continue;
    seen.add(target);
    refs.push({
      fullMatch: match[0],
      alt: match[1],
      target,
      isWikilink: false,
      isRemote: /^https?:\/\//i.test(target)
    });
  }
  const wikiRegex = /!\[\[([^\]]+)\]\]/g;
  while ((match = wikiRegex.exec(content)) !== null) {
    const target = match[1];
    if (seen.has(target))
      continue;
    seen.add(target);
    refs.push({
      fullMatch: match[0],
      alt: target.replace(/\.[^.]+$/, ""),
      target,
      isWikilink: true,
      isRemote: false
    });
  }
  return refs;
}
function resolveWikilink(target, noteDir, vaultRoot) {
  const cleanTarget = target.split("|")[0].trim();
  const searchPaths = [
    path2.join(noteDir, cleanTarget),
    path2.join(vaultRoot, cleanTarget),
    path2.join(vaultRoot, "assets", cleanTarget),
    path2.join(vaultRoot, "img", cleanTarget)
  ];
  const imgDirs = findImageDirs(noteDir);
  for (const dir of imgDirs) {
    searchPaths.push(path2.join(dir, cleanTarget));
  }
  for (const dir of findImageDirs(vaultRoot)) {
    searchPaths.push(path2.join(dir, cleanTarget));
  }
  for (const p of searchPaths) {
    if (fs.existsSync(p))
      return p;
  }
  return null;
}
function findImageDirs(baseDir) {
  const dirs = [];
  try {
    const entries = fs.readdirSync(baseDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        dirs.push(path2.join(baseDir, entry.name));
      }
    }
  } catch {
  }
  return dirs;
}
function resolveImagePath(target, isWikilink, noteDir, vaultRoot) {
  if (path2.isAbsolute(target)) {
    return fs.existsSync(target) ? target : null;
  }
  if (isWikilink) {
    return resolveWikilink(target, noteDir, vaultRoot);
  }
  const decoded = decodeURIComponent(target);
  const resolved = path2.resolve(noteDir, decoded);
  if (fs.existsSync(resolved))
    return resolved;
  const vaultResolved = path2.resolve(vaultRoot, decoded);
  if (fs.existsSync(vaultResolved))
    return vaultResolved;
  return null;
}
async function uploadToPicGo(imagePath, picgoServer) {
  return new Promise((resolve3, reject) => {
    const fileData = fs.readFileSync(imagePath);
    const fileName = path2.basename(imagePath);
    const ext = path2.extname(fileName).toLowerCase();
    const mimeTypes = {
      ".png": "image/png",
      ".jpg": "image/jpeg",
      ".jpeg": "image/jpeg",
      ".gif": "image/gif",
      ".webp": "image/webp",
      ".svg": "image/svg+xml",
      ".bmp": "image/bmp"
    };
    const mimeType = mimeTypes[ext] || "image/png";
    const boundary = `----PicGo${Date.now()}`;
    const bodyStart = Buffer.from(
      `--${boundary}\r
Content-Disposition: form-data; name="files"; filename="${fileName}"\r
Content-Type: ${mimeType}\r
\r
`
    );
    const bodyEnd = Buffer.from(`\r
--${boundary}--\r
`);
    const requestBody = Buffer.concat([bodyStart, fileData, bodyEnd]);
    const url = new URL(picgoServer);
    const options = {
      hostname: url.hostname,
      port: url.port || 36677,
      path: "/upload",
      method: "POST",
      timeout: 3e4,
      headers: {
        "Content-Type": `multipart/form-data; boundary=${boundary}`,
        "Content-Length": String(requestBody.length)
      }
    };
    const req = http.request(options, (res) => {
      let data = "";
      res.on("data", (chunk) => data += chunk);
      res.on("end", () => {
        try {
          const result = JSON.parse(data);
          if (result.success && result.result && result.result.length > 0) {
            resolve3(result.result[0]);
          } else {
            reject(new Error(result.message || result.msg || "Upload failed"));
          }
        } catch {
          reject(new Error("Failed to parse PicGo response: " + data.slice(0, 200)));
        }
      });
    });
    req.on("timeout", () => {
      req.destroy();
      reject(new Error("PicGo upload timed out (30s)"));
    });
    req.on("error", (err) => {
      reject(new Error(`Cannot connect to PicGo at ${url.hostname}:${url.port} \u2014 is PicGo running? (${err.message})`));
    });
    req.write(requestBody);
    req.end();
  });
}
async function processImages(content, noteAbsPath, vaultRoot, picgoServer) {
  const refs = extractImageRefs(content);
  const localRefs = refs.filter((r) => !r.isRemote);
  if (localRefs.length === 0) {
    return { content, uploaded: 0, failed: 0, errors: [] };
  }
  const noteDir = path2.dirname(noteAbsPath);
  let result = content;
  let uploaded = 0;
  let failed = 0;
  const errors = [];
  const uploads = [];
  for (const ref of localRefs) {
    const absPath = resolveImagePath(ref.target, ref.isWikilink, noteDir, vaultRoot);
    if (absPath) {
      uploads.push({ ref, absPath });
    } else {
      failed++;
      errors.push(`Image not found: ${ref.target} in ${path2.basename(noteAbsPath)}`);
    }
  }
  for (const { ref, absPath } of uploads) {
    try {
      const cdnUrl = await uploadToPicGo(absPath, picgoServer);
      result = result.replace(ref.fullMatch, `![${ref.alt}](${cdnUrl})`);
      uploaded++;
    } catch (e) {
      failed++;
      errors.push(`Upload failed for ${ref.target}: ${e.message}`);
    }
  }
  return { content: result, uploaded, failed, errors };
}

// src/deployer.ts
var Deployer = class {
  constructor(blogPath, postsSubdir, topImg, comments, commitTemplate, vaultRoot, picgoServer) {
    this.blogPath = blogPath;
    this.postsSubdir = postsSubdir;
    this.topImg = topImg;
    this.comments = comments;
    this.commitTemplate = commitTemplate;
    this.vaultRoot = vaultRoot;
    this.picgoServer = picgoServer;
    this.git = null;
  }
  get postsPath() {
    return path3.join(this.blogPath, this.postsSubdir);
  }
  initGit() {
    this.git = new GitOperator(this.blogPath);
    return this.git;
  }
  getGit() {
    return this.git;
  }
  readFile(filePath) {
    const absPath = path3.isAbsolute(filePath) ? filePath : path3.join(this.vaultRoot, filePath);
    return fs2.readFileSync(absPath, "utf-8");
  }
  prepareItem(relativePath) {
    const absSourcePath = path3.join(this.vaultRoot, relativePath);
    const content = this.readFile(absSourcePath);
    const fileName = path3.basename(relativePath);
    const destPath = path3.join(this.postsPath, fileName);
    const { frontmatter } = parseFrontmatter(content);
    const title = frontmatter?.title || extractTitleFromContent(content) || path3.parse(fileName).name;
    const autoTags = extractTagsFromPath(relativePath);
    let tags = frontmatter?.tags || "";
    if (autoTags && !tags) {
      tags = autoTags;
    } else if (autoTags && tags) {
      const tagSet = /* @__PURE__ */ new Set([...tags.split(",").map((t) => t.trim()), ...autoTags.split(",").map((t) => t.trim())]);
      tags = [...tagSet].filter(Boolean).join(", ");
    }
    return { sourcePath: absSourcePath, destPath, title, tags, fileName, processImages: true };
  }
  async deployItem(item) {
    const content = this.readFile(item.sourcePath);
    const { body } = parseFrontmatter(content);
    let processedBody = body;
    let imagesUploaded = 0;
    let imagesFailed = 0;
    const imageErrors = [];
    if (item.processImages) {
      const result = await processImages(body, item.sourcePath, this.vaultRoot, this.picgoServer);
      processedBody = result.content;
      imagesUploaded = result.uploaded;
      imagesFailed = result.failed;
      imageErrors.push(...result.errors);
    }
    const fm = generateFrontmatter(item.title, item.tags, this.topImg, this.comments);
    const fmStr = generateFrontmatterString(fm);
    const newContent = fmStr + processedBody;
    fs2.writeFileSync(item.destPath, newContent, "utf-8");
    return { dest: item.destPath, imagesUploaded, imagesFailed, imageErrors };
  }
  async deployAll(items, pushToGit) {
    const git = this.initGit();
    if (!git.isRepo()) {
      return { success: false, message: "Blog path is not a git repository", count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    if (!fs2.existsSync(this.postsPath)) {
      return { success: false, message: `Posts directory not found: ${this.postsPath}`, count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    const deployed = [];
    let totalUploaded = 0;
    let totalFailed = 0;
    const allErrors = [];
    for (const item of items) {
      try {
        const { dest, imagesUploaded, imagesFailed, imageErrors } = await this.deployItem(item);
        deployed.push(dest);
        totalUploaded += imagesUploaded;
        totalFailed += imagesFailed;
        allErrors.push(...imageErrors);
      } catch (e) {
        return { success: false, message: `Failed to write ${item.fileName}: ${e.message}`, count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
      }
    }
    if (deployed.length === 0) {
      return { success: false, message: "No files deployed", count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    let msg = `Deployed ${deployed.length} note(s)`;
    if (totalUploaded > 0) {
      msg += ` | \u{1F5BC}\uFE0F ${totalUploaded} image(s) uploaded`;
    }
    if (totalFailed > 0) {
      msg += ` | \u26A0\uFE0F ${totalFailed} failed`;
    }
    if (pushToGit) {
      const relativePaths = deployed.map((d) => path3.relative(this.blogPath, d));
      const added = git.add(relativePaths);
      if (!added) {
        return { success: false, message: "git add failed", count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
      }
      const title = items.map((i) => i.title).join(", ");
      const commitMsg = git.getCommitMessageTemplate(this.commitTemplate, title);
      git.commit(commitMsg);
      const pushResult = git.push();
      if (!pushResult.success) {
        return {
          success: false,
          message: `${msg} but git push failed: ${pushResult.message}`,
          count: deployed.length,
          imagesUploaded: totalUploaded,
          imagesFailed: totalFailed,
          imageErrors: allErrors
        };
      }
      msg += " and pushed to GitHub";
    }
    return { success: true, message: msg, count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
  }
};

// src/scheduler.ts
var import_obsidian2 = require("obsidian");
var Scheduler = class {
  constructor(plugin) {
    this.queue = [];
    this.timer = null;
    this.statusBarItem = null;
    this.remainingSeconds = 0;
    this.countdownInterval = null;
    this.plugin = plugin;
  }
  add(item) {
    const exists = this.queue.some((q) => q.sourcePath === item.sourcePath);
    if (exists) {
      new import_obsidian2.Notice(`"${item.title}" is already in the deploy queue`);
      return;
    }
    this.queue.push(item);
    new import_obsidian2.Notice(`"${item.title}" added to deploy queue (${this.queue.length} pending)`);
    this.resetTimer();
  }
  remove(sourcePath) {
    this.queue = this.queue.filter((q) => q.sourcePath !== sourcePath);
    this.updateStatusBar();
    if (this.queue.length === 0) {
      this.clearTimer();
    }
  }
  getQueue() {
    return [...this.queue];
  }
  resetTimer() {
    this.clearTimer();
    const delayMinutes = this.plugin.settings.deployDelayMinutes;
    if (delayMinutes <= 0) {
      this.executeDeploy();
      return;
    }
    this.remainingSeconds = delayMinutes * 60;
    this.updateStatusBar();
    this.countdownInterval = setInterval(() => {
      this.remainingSeconds--;
      this.updateStatusBar();
      if (this.remainingSeconds <= 0) {
        this.clearCountdown();
        this.executeDeploy();
      }
    }, 1e3);
  }
  forceDeploy() {
    this.clearTimer();
    this.executeDeploy();
  }
  clearQueue() {
    this.queue = [];
    this.clearTimer();
    this.updateStatusBar();
    new import_obsidian2.Notice("Deploy queue cleared");
  }
  clearTimer() {
    this.clearCountdown();
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }
  clearCountdown() {
    if (this.countdownInterval) {
      clearInterval(this.countdownInterval);
      this.countdownInterval = null;
    }
  }
  updateStatusBar() {
    if (!this.statusBarItem) {
      this.statusBarItem = this.plugin.addStatusBarItem();
      this.statusBarItem.addClass("blog-deploy-status");
    }
    if (this.queue.length === 0) {
      this.statusBarItem.setText("");
      this.statusBarItem.style.display = "none";
    } else {
      const mins = Math.floor(this.remainingSeconds / 60);
      const secs = this.remainingSeconds % 60;
      const timeStr = `${mins}:${String(secs).padStart(2, "0")}`;
      this.statusBarItem.setText(`\u23F3 ${this.queue.length} note(s) pending | Deploy in ${timeStr}`);
      this.statusBarItem.style.display = "";
    }
  }
  async executeDeploy() {
    if (this.queue.length === 0)
      return;
    const items = [...this.queue];
    this.queue = [];
    this.clearTimer();
    this.updateStatusBar();
    new import_obsidian2.Notice(`Deploying ${items.length} note(s) to blog...`);
    const vaultRoot = this.plugin.app.vault.adapter.getBasePath?.() ?? "";
    const deployer = new Deployer(
      this.plugin.settings.blogPath,
      this.plugin.settings.postsSubdir,
      this.plugin.settings.topImg,
      this.plugin.settings.comments,
      this.plugin.settings.commitTemplate,
      vaultRoot,
      this.plugin.settings.picgoServer
    );
    const result = await deployer.deployAll(items, this.plugin.settings.autoPush);
    if (result.success) {
      new import_obsidian2.Notice(`\u2705 ${result.message}`);
    } else {
      new import_obsidian2.Notice(`\u274C ${result.message}`);
    }
    if (result.imageErrors.length > 0) {
      const errSummary = result.imageErrors.slice(0, 3).join("; ");
      const more = result.imageErrors.length > 3 ? ` (+${result.imageErrors.length - 3} more)` : "";
      new import_obsidian2.Notice(`\u26A0\uFE0F Image issues: ${errSummary}${more}`, 8e3);
    }
  }
};

// main.ts
var BlogDeployPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.scheduler = new Scheduler(this);
    this.addSettingTab(new BlogDeploySettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("\u{1F4E4} Deploy to blog").setIcon("send").onClick(() => {
              this.showDeployDialog(file);
            });
          });
        }
      })
    );
    this.addCommand({
      id: "deploy-to-blog",
      name: "Deploy current note to blog",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.showDeployDialog(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "deploy-now",
      name: "Force deploy all pending notes now",
      callback: () => {
        this.scheduler.forceDeploy();
      }
    });
    this.addCommand({
      id: "clear-queue",
      name: "Clear deploy queue",
      callback: () => {
        this.scheduler.clearQueue();
      }
    });
    this.addCommand({
      id: "show-queue",
      name: "Show deploy queue",
      callback: () => {
        const queue = this.scheduler.getQueue();
        if (queue.length === 0) {
          new import_obsidian3.Notice("Deploy queue is empty");
        } else {
          const names = queue.map((q) => `- ${q.title}`).join("\n");
          new import_obsidian3.Notice(`Deploy queue (${queue.length}):
${names}`, 8e3);
        }
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  showDeployDialog(file) {
    const vaultRoot = this.app.vault.adapter.getBasePath?.() ?? "";
    if (!vaultRoot) {
      new import_obsidian3.Notice("\u274C Failed to get vault root path");
      return;
    }
    let item = null;
    try {
      const deployer = new Deployer(
        this.settings.blogPath,
        this.settings.postsSubdir,
        this.settings.topImg,
        this.settings.comments,
        this.settings.commitTemplate,
        vaultRoot,
        this.settings.picgoServer
      );
      item = deployer.prepareItem(file.path);
    } catch (e) {
      new import_obsidian3.Notice(`\u274C Error reading file: ${e.message}`);
      return;
    }
    if (!item) {
      new import_obsidian3.Notice("\u274C Failed to prepare deploy item");
      return;
    }
    new DeployConfirmModal(this.app, item, (confirmedItem) => {
      if (confirmedItem) {
        this.scheduler.add(confirmedItem);
      }
    }).open();
  }
};
var DeployConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, item, onSubmit) {
    super(app);
    this.item = item;
    this.onSubmit = onSubmit;
    this.titleInput = document.createElement("input");
    this.tagsInput = document.createElement("input");
    this.processImagesCheckbox = document.createElement("input");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("blog-deploy-modal");
    contentEl.createEl("h2", { text: "\u{1F4E4} Deploy to Blog" });
    contentEl.createEl("p", {
      text: `File: ${this.item.fileName}`,
      cls: "blog-deploy-file"
    });
    const titleSetting = contentEl.createDiv();
    titleSetting.createEl("label", { text: "Title" });
    this.titleInput = titleSetting.createEl("input", {
      type: "text",
      value: this.item.title
    });
    this.titleInput.style.width = "100%";
    this.titleInput.style.marginBottom = "12px";
    const tagsSetting = contentEl.createDiv();
    tagsSetting.createEl("label", { text: "Tags (comma-separated)" });
    this.tagsInput = tagsSetting.createEl("input", {
      type: "text",
      value: this.item.tags,
      placeholder: "e.g. Java, \u7B14\u8BB0"
    });
    this.tagsInput.style.width = "100%";
    this.tagsInput.style.marginBottom = "12px";
    const imageSetting = contentEl.createDiv();
    imageSetting.style.display = "flex";
    imageSetting.style.alignItems = "center";
    imageSetting.style.gap = "8px";
    imageSetting.style.marginBottom = "12px";
    this.processImagesCheckbox = imageSetting.createEl("input", {
      type: "checkbox"
    });
    this.processImagesCheckbox.checked = true;
    this.processImagesCheckbox.id = "blog-deploy-process-images";
    imageSetting.createEl("label", {
      text: "\u{1F5BC}\uFE0F Upload local images to CDN (PicGo)",
      cls: "blog-deploy-checkbox-label"
    });
    const label = imageSetting.querySelector("label");
    if (label)
      label.setAttribute("for", "blog-deploy-process-images");
    contentEl.createEl("p", {
      text: `Destination: ${this.item.destPath}`,
      cls: "blog-deploy-path"
    });
    const buttonRow = contentEl.createDiv();
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";
    buttonRow.style.gap = "8px";
    buttonRow.style.marginTop = "16px";
    const cancelBtn = buttonRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.onSubmit(null);
      this.close();
    };
    const deployBtn = buttonRow.createEl("button", {
      text: "\u2705 Add to queue",
      cls: "mod-cta"
    });
    deployBtn.onclick = () => {
      this.item.title = this.titleInput.value.trim() || this.item.title;
      this.item.tags = this.tagsInput.value.trim() || this.item.tags;
      this.item.processImages = this.processImagesCheckbox.checked;
      this.onSubmit(this.item);
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
