/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BlogDeployPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  blogPath: "C:\\Users\\yelfs\\Desktop\\My-Blog",
  postsSubdir: "source\\_posts",
  deployDelayMinutes: 10,
  autoPush: true,
  topImg: "transparent",
  comments: false,
  commitTemplate: "publish: {{title}} via Obsidian",
  picgoServer: "http://127.0.0.1:36677"
};
var BlogDeploySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u535A\u5BA2\u90E8\u7F72\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u535A\u5BA2\u672C\u5730\u8DEF\u5F84").setDesc("Hexo/Hugo \u535A\u5BA2 Git \u4ED3\u5E93\u7684\u7EDD\u5BF9\u8DEF\u5F84").addText(
      (text) => text.setPlaceholder("C:\\Users\\yelfs\\Desktop\\My-Blog").setValue(this.plugin.settings.blogPath).onChange(async (value) => {
        this.plugin.settings.blogPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u7AE0\u5B50\u76EE\u5F55").setDesc("\u535A\u5BA2\u6839\u76EE\u5F55\u4E0B\u7684 _posts \u6587\u4EF6\u5939\u76F8\u5BF9\u8DEF\u5F84").addText(
      (text) => text.setPlaceholder("source/_posts").setValue(this.plugin.settings.postsSubdir).onChange(async (value) => {
        this.plugin.settings.postsSubdir = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u90E8\u7F72\u5EF6\u8FDF\uFF08\u5206\u949F\uFF09").setDesc("\u7B49\u5F85\u591A\u4E45\u540E\u81EA\u52A8\u90E8\u7F72\uFF080 = \u7ACB\u5373\u90E8\u7F72\uFF09").addSlider(
      (slider) => slider.setLimits(0, 60, 1).setValue(this.plugin.settings.deployDelayMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.deployDelayMinutes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8 Git Push").setDesc("\u90E8\u7F72\u540E\u81EA\u52A8\u63D0\u4EA4\u5E76\u63A8\u9001\u5230 GitHub").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoPush).onChange(async (value) => {
        this.plugin.settings.autoPush = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5F00\u542F\u8BC4\u8BBA").setDesc("\u6587\u7AE0\u5934\u90E8\u7684 comments \u9ED8\u8BA4\u503C").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.comments).onChange(async (value) => {
        this.plugin.settings.comments = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u9876\u90E8\u56FE\u7247").setDesc("\u6587\u7AE0\u5934\u90E8\u7684 top_img \u9ED8\u8BA4\u503C\uFF08\u4F8B\u5982 transparent \u6216\u56FE\u7247 URL\uFF09").addText(
      (text) => text.setValue(this.plugin.settings.topImg).onChange(async (value) => {
        this.plugin.settings.topImg = value || "transparent";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u63D0\u4EA4\u4FE1\u606F\u6A21\u677F").setDesc("\u4F7F\u7528 {{title}} \u4F5C\u4E3A\u6587\u7AE0\u6807\u9898\u7684\u5360\u4F4D\u7B26").addText(
      (text) => text.setPlaceholder("publish: {{title}} via Obsidian").setValue(this.plugin.settings.commitTemplate).onChange(async (value) => {
        this.plugin.settings.commitTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("PicGo \u670D\u52A1\u5668\u5730\u5740").setDesc("PicGo \u672C\u5730\u4E0A\u4F20\u670D\u52A1\u5668\u5730\u5740\uFF08PicGo \u2192 \u8BBE\u7F6E \u2192 Server\uFF09").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:36677").setValue(this.plugin.settings.picgoServer).onChange(async (value) => {
        this.plugin.settings.picgoServer = value || "http://127.0.0.1:36677";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/deployer.ts
var path3 = __toESM(require("path"));
var fs2 = __toESM(require("fs"));

// src/frontmatter.ts
function parseFrontmatter(content) {
  if (!content.startsWith("---")) {
    return { frontmatter: null, body: content };
  }
  const endIndex = content.indexOf("---", 3);
  if (endIndex === -1) {
    return { frontmatter: null, body: content };
  }
  const fmSection = content.substring(3, endIndex).trim();
  const body = content.substring(endIndex + 3).trimStart();
  const lines = fmSection.split("\n");
  const frontmatter = {};
  for (const line of lines) {
    const colonIndex = line.indexOf(":");
    if (colonIndex === -1)
      continue;
    const key = line.substring(0, colonIndex).trim();
    let value = line.substring(colonIndex + 1).trim();
    if (value === "false") {
      frontmatter[key] = false;
    } else if (value === "true") {
      frontmatter[key] = true;
    } else {
      frontmatter[key] = value;
    }
  }
  return { frontmatter, body };
}
function generateFrontmatterString(fm) {
  let result = "---\n";
  result += `title: ${fm.title}
`;
  result += `tags: ${fm.tags}
`;
  result += `date: ${fm.date}
`;
  result += `top_img: ${fm.top_img}
`;
  result += `comments: ${fm.comments}
`;
  result += "---\n\n";
  return result;
}
function generateFrontmatter(title, tags, topImg, comments) {
  const today = /* @__PURE__ */ new Date();
  const y = today.getFullYear();
  const m = String(today.getMonth() + 1).padStart(2, "0");
  const d = String(today.getDate()).padStart(2, "0");
  return {
    title,
    tags,
    date: `${y}-${m}-${d}`,
    top_img: topImg,
    comments
  };
}
function extractTitleFromContent(content) {
  const match = content.match(/^#\s+(.+)$/m);
  if (match && match[1]) {
    return match[1].trim();
  }
  return "";
}
function extractTagsFromPath(filePath) {
  const parts = filePath.replace(/\\/g, "/").split("/");
  if (parts.length <= 1) {
    return "";
  }
  const folders = parts.slice(0, -1);
  return folders.filter((f) => f.trim().length > 0 && !f.startsWith(".")).join(", ");
}

// src/git.ts
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var GitOperator = class {
  constructor(repoPath) {
    this.repoPath = repoPath;
  }
  exec(cmd) {
    const options = {
      cwd: this.repoPath,
      encoding: "utf-8",
      timeout: 3e4,
      stdio: ["pipe", "pipe", "pipe"],
      windowsHide: true
    };
    try {
      const stdout = (0, import_child_process.execSync)(cmd, options);
      return { stdout: stdout.toString().trim(), stderr: "" };
    } catch (e) {
      return {
        stdout: e.stdout?.toString().trim() || "",
        stderr: e.stderr?.toString().trim() || e.message
      };
    }
  }
  isRepo() {
    const dir = path.resolve(this.repoPath);
    const dotGit = path.join(dir, ".git");
    try {
      require("fs").statSync(dotGit);
      return true;
    } catch {
      return false;
    }
  }
  hasUnsavedChanges() {
    const { stdout } = this.exec("git status --porcelain");
    return stdout.length > 0;
  }
  add(files) {
    const fileArgs = files.map((f) => `"${f}"`).join(" ");
    const { stderr } = this.exec(`git add ${fileArgs}`);
    if (stderr) {
      console.error("git add error:", stderr);
      return false;
    }
    return true;
  }
  commit(message) {
    const { stderr } = this.exec(`git commit -m "${message.replace(/"/g, '\\"')}"`);
    if (stderr && !stderr.includes("nothing to commit") && !stderr.includes("nothing added")) {
      console.error("git commit error:", stderr);
      return false;
    }
    return true;
  }
  push(branch = "main") {
    const { stdout, stderr } = this.exec(`git push origin ${branch}`);
    if (stderr && stderr.includes("error")) {
      return { success: false, message: stderr };
    }
    return { success: true, message: stdout || "Pushed successfully" };
  }
  getCurrentBranch() {
    const { stdout } = this.exec("git rev-parse --abbrev-ref HEAD");
    return stdout || "main";
  }
  getCommitMessageTemplate(template, title) {
    return template.replace("{{title}}", title);
  }
};

// src/images.ts
var fs = __toESM(require("fs"));
var path2 = __toESM(require("path"));
var os = __toESM(require("os"));
var import_child_process2 = require("child_process");
function extractImageRefs(content) {
  const refs = [];
  const seen = /* @__PURE__ */ new Set();
  const mdRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  let match;
  while ((match = mdRegex.exec(content)) !== null) {
    const target = match[2];
    if (seen.has(target))
      continue;
    seen.add(target);
    refs.push({
      fullMatch: match[0],
      alt: match[1],
      target,
      isWikilink: false,
      isRemote: /^https?:\/\//i.test(target)
    });
  }
  const wikiRegex = /!\[\[([^\]]+)\]\]/g;
  while ((match = wikiRegex.exec(content)) !== null) {
    const target = match[1];
    if (seen.has(target))
      continue;
    seen.add(target);
    refs.push({
      fullMatch: match[0],
      alt: target.replace(/\.[^.]+$/, ""),
      target,
      isWikilink: true,
      isRemote: false
    });
  }
  return refs;
}
function resolveWikilink(target, noteDir, vaultRoot) {
  const cleanTarget = target.split("|")[0].trim();
  const searchPaths = [
    path2.join(noteDir, cleanTarget),
    path2.join(vaultRoot, cleanTarget),
    path2.join(vaultRoot, "assets", cleanTarget),
    path2.join(vaultRoot, "img", cleanTarget)
  ];
  const imgDirs = findImageDirs(noteDir);
  for (const dir of imgDirs) {
    searchPaths.push(path2.join(dir, cleanTarget));
  }
  for (const dir of findImageDirs(vaultRoot)) {
    searchPaths.push(path2.join(dir, cleanTarget));
  }
  for (const p of searchPaths) {
    if (fs.existsSync(p))
      return p;
  }
  return null;
}
function findImageDirs(baseDir) {
  const dirs = [];
  try {
    const entries = fs.readdirSync(baseDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        dirs.push(path2.join(baseDir, entry.name));
      }
    }
  } catch {
  }
  return dirs;
}
function resolveImagePath(target, isWikilink, noteDir, vaultRoot) {
  if (path2.isAbsolute(target)) {
    return fs.existsSync(target) ? target : null;
  }
  if (isWikilink) {
    return resolveWikilink(target, noteDir, vaultRoot);
  }
  const decoded = decodeURIComponent(target);
  const resolved = path2.resolve(noteDir, decoded);
  if (fs.existsSync(resolved))
    return resolved;
  const vaultResolved = path2.resolve(vaultRoot, decoded);
  if (fs.existsSync(vaultResolved))
    return vaultResolved;
  return null;
}
async function uploadToPicGo(imagePath, picgoServer) {
  return new Promise((resolve3, reject) => {
    const ext = path2.extname(imagePath);
    const tmpFile = path2.join(os.tmpdir(), `picgo_upload_${Date.now()}${ext}`);
    let tmpCreated = false;
    try {
      fs.copyFileSync(imagePath, tmpFile);
      tmpCreated = true;
      const cmd = `curl.exe -s -X POST "${picgoServer}/upload" -F "files=@${tmpFile}" --connect-timeout 10 -m 40`;
      const stdout = (0, import_child_process2.execSync)(cmd, {
        encoding: "utf-8",
        timeout: 45e3,
        windowsHide: true,
        stdio: ["pipe", "pipe", "pipe"]
      });
      try {
        const result = JSON.parse(stdout);
        if (result.success && result.result && result.result.length > 0) {
          resolve3(result.result[0]);
        } else {
          reject(new Error(result.message || result.msg || "\u4E0A\u4F20\u5931\u8D25\uFF1A\u7A7A\u54CD\u5E94"));
        }
      } catch {
        reject(new Error("\u89E3\u6790 PicGo \u54CD\u5E94\u5931\u8D25\uFF1A" + stdout.slice(0, 200)));
      }
    } catch (e) {
      const stderr = e.stderr?.toString() || e.stdout?.toString() || e.message || "";
      reject(new Error(stderr.slice(0, 200)));
    } finally {
      if (tmpCreated) {
        try {
          fs.unlinkSync(tmpFile);
        } catch {
        }
      }
    }
  });
}
async function processImages(content, noteAbsPath, vaultRoot, picgoServer) {
  const refs = extractImageRefs(content);
  const localRefs = refs.filter((r) => !r.isRemote);
  if (localRefs.length === 0) {
    return { content, uploaded: 0, failed: 0, errors: [] };
  }
  const noteDir = path2.dirname(noteAbsPath);
  let result = content;
  let uploaded = 0;
  let failed = 0;
  const errors = [];
  const uploads = [];
  for (const ref of localRefs) {
    const absPath = resolveImagePath(ref.target, ref.isWikilink, noteDir, vaultRoot);
    if (absPath) {
      uploads.push({ ref, absPath });
    } else {
      failed++;
      errors.push(`\u627E\u4E0D\u5230\u56FE\u7247\uFF1A${ref.target}\uFF08\u5728 ${path2.basename(noteAbsPath)} \u4E2D\uFF09`);
    }
  }
  for (const { ref, absPath } of uploads) {
    try {
      const cdnUrl = await uploadToPicGo(absPath, picgoServer);
      result = result.replace(ref.fullMatch, `![${ref.alt}](${cdnUrl})`);
      uploaded++;
    } catch (e) {
      failed++;
      errors.push(`\u4E0A\u4F20\u5931\u8D25 ${ref.target}\uFF1A${e.message}`);
    }
  }
  return { content: result, uploaded, failed, errors };
}

// src/deployer.ts
function sanitizeFolderName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").trim();
}
function computeSubfolder(tags) {
  const firstTag = tags.split(",")[0]?.trim();
  if (!firstTag)
    return "\u672A\u5206\u7C7B";
  const sanitized = sanitizeFolderName(firstTag);
  return sanitized || "\u672A\u5206\u7C7B";
}
function collectTagsFromFile(filePath) {
  try {
    const content = fs2.readFileSync(filePath, "utf-8");
    const { frontmatter } = parseFrontmatter(content);
    if (frontmatter?.tags) {
      return frontmatter.tags.toString().split(",").map((t) => t.trim()).filter(Boolean);
    }
  } catch {
  }
  return [];
}
var Deployer = class {
  constructor(blogPath, postsSubdir, topImg, comments, commitTemplate, vaultRoot, picgoServer) {
    this.blogPath = blogPath;
    this.postsSubdir = postsSubdir;
    this.topImg = topImg;
    this.comments = comments;
    this.commitTemplate = commitTemplate;
    this.vaultRoot = vaultRoot;
    this.picgoServer = picgoServer;
    this.git = null;
  }
  get postsPath() {
    return path3.join(this.blogPath, this.postsSubdir);
  }
  getExistingTags() {
    const tagSet = /* @__PURE__ */ new Set();
    try {
      const walkDir = (dir) => {
        const entries = fs2.readdirSync(dir, { withFileTypes: true });
        for (const entry of entries) {
          const fullPath = path3.join(dir, entry.name);
          if (entry.isDirectory()) {
            walkDir(fullPath);
          } else if (entry.isFile() && entry.name.endsWith(".md")) {
            const tags = collectTagsFromFile(fullPath);
            for (const t of tags) {
              tagSet.add(t);
            }
          }
        }
      };
      walkDir(this.postsPath);
    } catch {
    }
    return [...tagSet].sort();
  }
  initGit() {
    this.git = new GitOperator(this.blogPath);
    return this.git;
  }
  getGit() {
    return this.git;
  }
  readFile(filePath) {
    const absPath = path3.isAbsolute(filePath) ? filePath : path3.join(this.vaultRoot, filePath);
    return fs2.readFileSync(absPath, "utf-8");
  }
  prepareItem(relativePath) {
    const absSourcePath = path3.join(this.vaultRoot, relativePath);
    const content = this.readFile(absSourcePath);
    const fileName = path3.basename(relativePath);
    const { frontmatter } = parseFrontmatter(content);
    const title = frontmatter?.title || extractTitleFromContent(content) || path3.parse(fileName).name;
    const autoTags = extractTagsFromPath(relativePath);
    let tags = frontmatter?.tags || "";
    if (autoTags && !tags) {
      tags = autoTags;
    } else if (autoTags && tags) {
      const tagSet = /* @__PURE__ */ new Set([...tags.split(",").map((t) => t.trim()), ...autoTags.split(",").map((t) => t.trim())]);
      tags = [...tagSet].filter(Boolean).join(", ");
    }
    const subfolder = computeSubfolder(tags);
    const destPath = path3.join(this.postsPath, subfolder, fileName);
    return { sourcePath: absSourcePath, destPath, title, tags, fileName, processImages: true };
  }
  async deployItem(item) {
    const content = this.readFile(item.sourcePath);
    const { body } = parseFrontmatter(content);
    let processedBody = body;
    let imagesUploaded = 0;
    let imagesFailed = 0;
    const imageErrors = [];
    if (item.processImages) {
      const result = await processImages(body, item.sourcePath, this.vaultRoot, this.picgoServer);
      processedBody = result.content;
      imagesUploaded = result.uploaded;
      imagesFailed = result.failed;
      imageErrors.push(...result.errors);
    }
    const fm = generateFrontmatter(item.title, item.tags, this.topImg, this.comments);
    const fmStr = generateFrontmatterString(fm);
    const newContent = fmStr + processedBody;
    const destDir = path3.dirname(item.destPath);
    if (!fs2.existsSync(destDir)) {
      fs2.mkdirSync(destDir, { recursive: true });
    }
    fs2.writeFileSync(item.destPath, newContent, "utf-8");
    return { dest: item.destPath, imagesUploaded, imagesFailed, imageErrors };
  }
  async deployAll(items, pushToGit) {
    const git = this.initGit();
    if (!git.isRepo()) {
      return { success: false, message: "\u535A\u5BA2\u8DEF\u5F84\u4E0D\u662F\u4E00\u4E2A Git \u4ED3\u5E93", count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    if (!fs2.existsSync(this.postsPath)) {
      return { success: false, message: `\u6587\u7AE0\u76EE\u5F55\u4E0D\u5B58\u5728\uFF1A${this.postsPath}`, count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    const deployed = [];
    let totalUploaded = 0;
    let totalFailed = 0;
    const allErrors = [];
    for (const item of items) {
      try {
        const { dest, imagesUploaded, imagesFailed, imageErrors } = await this.deployItem(item);
        deployed.push(dest);
        totalUploaded += imagesUploaded;
        totalFailed += imagesFailed;
        allErrors.push(...imageErrors);
      } catch (e) {
        return { success: false, message: `\u5199\u5165 ${item.fileName} \u5931\u8D25\uFF1A${e.message}`, count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
      }
    }
    if (deployed.length === 0) {
      return { success: false, message: "\u6CA1\u6709\u6587\u4EF6\u88AB\u90E8\u7F72", count: 0, imagesUploaded: 0, imagesFailed: 0, imageErrors: [] };
    }
    let msg = `\u6210\u529F\u90E8\u7F72 ${deployed.length} \u7BC7\u7B14\u8BB0`;
    if (totalUploaded > 0) {
      msg += ` | \u{1F5BC}\uFE0F ${totalUploaded} \u5F20\u56FE\u7247\u5DF2\u4E0A\u4F20`;
    }
    if (totalFailed > 0) {
      msg += ` | \u26A0\uFE0F ${totalFailed} \u5F20\u5931\u8D25`;
    }
    if (pushToGit) {
      const relativePaths = deployed.map((d) => path3.relative(this.blogPath, d));
      const added = git.add(relativePaths);
      if (!added) {
        return { success: false, message: "git add \u5931\u8D25", count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
      }
      const title = items.map((i) => i.title).join(", ");
      const commitMsg = git.getCommitMessageTemplate(this.commitTemplate, title);
      git.commit(commitMsg);
      const pushResult = git.push();
      if (!pushResult.success) {
        return {
          success: false,
          message: `${msg}\uFF0C\u4F46 git push \u5931\u8D25\uFF1A${pushResult.message}`,
          count: deployed.length,
          imagesUploaded: totalUploaded,
          imagesFailed: totalFailed,
          imageErrors: allErrors
        };
      }
      msg += "\uFF0C\u5DF2\u63A8\u9001\u81F3 GitHub";
    }
    return { success: true, message: msg, count: deployed.length, imagesUploaded: totalUploaded, imagesFailed: totalFailed, imageErrors: allErrors };
  }
};

// src/scheduler.ts
var import_obsidian2 = require("obsidian");
var Scheduler = class {
  constructor(plugin) {
    this.queue = [];
    this.timer = null;
    this.statusBarItem = null;
    this.remainingSeconds = 0;
    this.countdownInterval = null;
    this.plugin = plugin;
  }
  add(item) {
    const exists = this.queue.some((q) => q.sourcePath === item.sourcePath);
    if (exists) {
      new import_obsidian2.Notice(`"${item.title}" \u5DF2\u5728\u90E8\u7F72\u961F\u5217\u4E2D`);
      return;
    }
    this.queue.push(item);
    new import_obsidian2.Notice(`"${item.title}" \u5DF2\u52A0\u5165\u961F\u5217\uFF08\u5171 ${this.queue.length} \u7BC7\u5F85\u5904\u7406\uFF09`);
    this.resetTimer();
  }
  remove(sourcePath) {
    this.queue = this.queue.filter((q) => q.sourcePath !== sourcePath);
    this.updateStatusBar();
    if (this.queue.length === 0) {
      this.clearTimer();
    }
  }
  getQueue() {
    return [...this.queue];
  }
  resetTimer() {
    this.clearTimer();
    const delayMinutes = this.plugin.settings.deployDelayMinutes;
    if (delayMinutes <= 0) {
      this.executeDeploy();
      return;
    }
    this.remainingSeconds = delayMinutes * 60;
    this.updateStatusBar();
    this.countdownInterval = setInterval(() => {
      this.remainingSeconds--;
      this.updateStatusBar();
      if (this.remainingSeconds <= 0) {
        this.clearCountdown();
        this.executeDeploy();
      }
    }, 1e3);
  }
  forceDeploy() {
    this.clearTimer();
    this.executeDeploy();
  }
  clearQueue() {
    this.queue = [];
    this.clearTimer();
    this.updateStatusBar();
    new import_obsidian2.Notice("\u90E8\u7F72\u961F\u5217\u5DF2\u6E05\u7A7A");
  }
  clearTimer() {
    this.clearCountdown();
    if (this.timer) {
      clearTimeout(this.timer);
      this.timer = null;
    }
  }
  clearCountdown() {
    if (this.countdownInterval) {
      clearInterval(this.countdownInterval);
      this.countdownInterval = null;
    }
  }
  updateStatusBar() {
    if (!this.statusBarItem) {
      this.statusBarItem = this.plugin.addStatusBarItem();
      this.statusBarItem.addClass("blog-deploy-status");
      this.statusBarItem.style.cursor = "default";
    }
    if (this.queue.length === 0) {
      this.statusBarItem.setText("");
      this.statusBarItem.style.display = "none";
    } else {
      this.statusBarItem.empty();
      const mins = Math.floor(this.remainingSeconds / 60);
      const secs = this.remainingSeconds % 60;
      const timeStr = `${mins}:${String(secs).padStart(2, "0")}`;
      const label = this.statusBarItem.createSpan({
        text: `\u23F3 ${this.queue.length} \u7BC7\u5F85\u90E8\u7F72 | \u5269\u4F59 ${timeStr}`
      });
      const forceBtn = this.statusBarItem.createEl("a", {
        text: "\u7ACB\u5373\u63A8\u9001",
        cls: "blog-deploy-status-btn"
      });
      forceBtn.style.cssText = "margin-left:8px;cursor:pointer;color:var(--text-accent);";
      forceBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.forceDeploy();
      };
      const cancelBtn = this.statusBarItem.createEl("a", {
        text: "\u53D6\u6D88\u5168\u90E8",
        cls: "blog-deploy-status-btn"
      });
      cancelBtn.style.cssText = "margin-left:4px;cursor:pointer;color:var(--text-error);";
      cancelBtn.onclick = (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.clearQueue();
      };
      this.statusBarItem.style.display = "";
    }
  }
  async executeDeploy() {
    if (this.queue.length === 0)
      return;
    const items = [...this.queue];
    this.queue = [];
    this.clearTimer();
    this.updateStatusBar();
    new import_obsidian2.Notice(`\u6B63\u5728\u90E8\u7F72 ${items.length} \u7BC7\u7B14\u8BB0\u5230\u535A\u5BA2...`);
    const vaultRoot = this.plugin.app.vault.adapter.getBasePath?.() ?? "";
    const deployer = new Deployer(
      this.plugin.settings.blogPath,
      this.plugin.settings.postsSubdir,
      this.plugin.settings.topImg,
      this.plugin.settings.comments,
      this.plugin.settings.commitTemplate,
      vaultRoot,
      this.plugin.settings.picgoServer
    );
    const result = await deployer.deployAll(items, this.plugin.settings.autoPush);
    if (result.success) {
      new import_obsidian2.Notice(`\u2705 ${result.message}`);
    } else {
      new import_obsidian2.Notice(`\u274C ${result.message}`);
    }
    if (result.imageErrors.length > 0) {
      const errSummary = result.imageErrors.slice(0, 3).join("; ");
      const more = result.imageErrors.length > 3 ? `\uFF08\u8FD8\u6709 ${result.imageErrors.length - 3} \u4E2A\u9519\u8BEF\uFF09` : "";
      new import_obsidian2.Notice(`\u26A0\uFE0F \u56FE\u7247\u95EE\u9898\uFF1A${errSummary}${more}`, 8e3);
    }
  }
};

// main.ts
var BlogDeployPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.scheduler = new Scheduler(this);
    this.addSettingTab(new BlogDeploySettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("\u{1F4E4} \u90E8\u7F72\u5230\u535A\u5BA2").setIcon("send").onClick(() => {
              this.showDeployDialog(file);
            });
          });
        }
      })
    );
    this.addCommand({
      id: "deploy-to-blog",
      name: "\u90E8\u7F72\u5F53\u524D\u7B14\u8BB0\u5230\u535A\u5BA2",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.showDeployDialog(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "deploy-now",
      name: "\u7ACB\u5373\u90E8\u7F72\u961F\u5217\u4E2D\u7684\u6240\u6709\u7B14\u8BB0",
      callback: () => {
        this.scheduler.forceDeploy();
      }
    });
    this.addCommand({
      id: "clear-queue",
      name: "\u6E05\u7A7A\u90E8\u7F72\u961F\u5217",
      callback: () => {
        this.scheduler.clearQueue();
      }
    });
    this.addCommand({
      id: "show-queue",
      name: "\u67E5\u770B\u90E8\u7F72\u961F\u5217",
      callback: () => {
        const queue = this.scheduler.getQueue();
        if (queue.length === 0) {
          new import_obsidian3.Notice("\u90E8\u7F72\u961F\u5217\u4E3A\u7A7A");
        } else {
          const names = queue.map((q) => `- ${q.title}`).join("\n");
          new import_obsidian3.Notice(`\u90E8\u7F72\u961F\u5217\uFF08${queue.length} \u7BC7\uFF09\uFF1A
${names}`, 8e3);
        }
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  showDeployDialog(file) {
    const vaultRoot = this.app.vault.adapter.getBasePath?.() ?? "";
    if (!vaultRoot) {
      new import_obsidian3.Notice("\u274C \u83B7\u53D6 vault \u6839\u8DEF\u5F84\u5931\u8D25");
      return;
    }
    let item = null;
    let existingTags = [];
    try {
      const deployer = new Deployer(
        this.settings.blogPath,
        this.settings.postsSubdir,
        this.settings.topImg,
        this.settings.comments,
        this.settings.commitTemplate,
        vaultRoot,
        this.settings.picgoServer
      );
      item = deployer.prepareItem(file.path);
      existingTags = deployer.getExistingTags();
    } catch (e) {
      new import_obsidian3.Notice(`\u274C \u8BFB\u53D6\u6587\u4EF6\u51FA\u9519\uFF1A${e.message}`);
      return;
    }
    if (!item) {
      new import_obsidian3.Notice("\u274C \u51C6\u5907\u90E8\u7F72\u9879\u5931\u8D25");
      return;
    }
    new DeployConfirmModal(this.app, item, existingTags, (confirmedItem) => {
      if (confirmedItem) {
        this.scheduler.add(confirmedItem);
      }
    }).open();
  }
};
var DeployConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, item, existingTags, onSubmit) {
    super(app);
    this.item = item;
    this.existingTags = existingTags;
    this.onSubmit = onSubmit;
    this.titleInput = document.createElement("input");
    this.tagsInput = document.createElement("input");
    this.processImagesCheckbox = document.createElement("input");
    this.destHint = document.createElement("p");
  }
  updateDestHint() {
    const tags = this.tagsInput.value.trim() || this.item.tags;
    const subfolder = tags.split(",")[0]?.trim() || "\u672A\u5206\u7C7B";
    const sanitized = subfolder.replace(/[\\/:*?"<>|]/g, "_").trim() || "\u672A\u5206\u7C7B";
    this.destHint.setText(`\u76EE\u6807\u4F4D\u7F6E\uFF1Asource/_posts/${sanitized}/${this.item.fileName}`);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("blog-deploy-modal");
    contentEl.createEl("h2", { text: "\u{1F4E4} \u90E8\u7F72\u5230\u535A\u5BA2" });
    contentEl.createEl("p", {
      text: `\u6587\u4EF6\uFF1A${this.item.fileName}`,
      cls: "blog-deploy-file"
    });
    const titleSetting = contentEl.createDiv();
    titleSetting.createEl("label", { text: "\u6807\u9898" });
    this.titleInput = titleSetting.createEl("input", {
      type: "text",
      value: this.item.title
    });
    this.titleInput.style.width = "100%";
    this.titleInput.style.marginBottom = "12px";
    const tagsSetting = contentEl.createDiv();
    tagsSetting.createEl("label", { text: "\u6807\u7B7E\uFF08\u9017\u53F7\u5206\u9694\uFF09" });
    this.tagsInput = tagsSetting.createEl("input", {
      type: "text",
      value: this.item.tags,
      placeholder: "\u4F8B\u5982\uFF1AJava, \u7B14\u8BB0"
    });
    this.tagsInput.style.width = "100%";
    this.tagsInput.style.marginBottom = "6px";
    this.tagsInput.oninput = () => this.updateDestHint();
    if (this.existingTags.length > 0) {
      const chipRow = tagsSetting.createDiv();
      chipRow.style.display = "flex";
      chipRow.style.flexWrap = "wrap";
      chipRow.style.gap = "4px";
      chipRow.style.marginBottom = "12px";
      chipRow.createEl("span", {
        text: "\u5DF2\u6709\u6807\u7B7E\uFF1A",
        cls: "blog-deploy-chip-label"
      });
      for (const tag of this.existingTags) {
        const chip = chipRow.createEl("span", {
          text: tag,
          cls: "blog-deploy-tag-chip"
        });
        chip.style.cssText = `
          display: inline-block;
          padding: 2px 8px;
          background: var(--interactive-normal);
          border-radius: 10px;
          font-size: 12px;
          cursor: pointer;
          user-select: none;
        `;
        chip.onmouseenter = () => {
          chip.style.background = "var(--interactive-accent)";
          chip.style.color = "var(--text-on-accent)";
        };
        chip.onmouseleave = () => {
          chip.style.background = "var(--interactive-normal)";
          chip.style.color = "";
        };
        chip.onclick = () => {
          const currentTags = this.tagsInput.value.split(",").map((t) => t.trim()).filter(Boolean);
          const idx = currentTags.indexOf(tag);
          if (idx >= 0) {
            currentTags.splice(idx, 1);
          } else {
            currentTags.push(tag);
          }
          this.tagsInput.value = currentTags.join(", ");
          this.updateDestHint();
        };
      }
    }
    const imageSetting = contentEl.createDiv();
    imageSetting.style.display = "flex";
    imageSetting.style.alignItems = "center";
    imageSetting.style.gap = "8px";
    imageSetting.style.marginBottom = "12px";
    this.processImagesCheckbox = imageSetting.createEl("input", {
      type: "checkbox"
    });
    this.processImagesCheckbox.checked = true;
    this.processImagesCheckbox.id = "blog-deploy-process-images";
    imageSetting.createEl("label", {
      text: "\u{1F5BC}\uFE0F \u4E0A\u4F20\u672C\u5730\u56FE\u7247\u5230\u56FE\u5E8A (PicGo)",
      cls: "blog-deploy-checkbox-label"
    });
    const label = imageSetting.querySelector("label");
    if (label)
      label.setAttribute("for", "blog-deploy-process-images");
    this.destHint = contentEl.createEl("p", {
      cls: "blog-deploy-path"
    });
    this.updateDestHint();
    const buttonRow = contentEl.createDiv();
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "flex-end";
    buttonRow.style.gap = "8px";
    buttonRow.style.marginTop = "16px";
    const cancelBtn = buttonRow.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => {
      this.onSubmit(null);
      this.close();
    };
    const deployBtn = buttonRow.createEl("button", {
      text: "\u2705 \u52A0\u5165\u961F\u5217",
      cls: "mod-cta"
    });
    deployBtn.onclick = () => {
      this.item.title = this.titleInput.value.trim() || this.item.title;
      this.item.tags = this.tagsInput.value.trim() || this.item.tags;
      this.item.processImages = this.processImagesCheckbox.checked;
      this.onSubmit(this.item);
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
